import { Ubuntu } from "next/font/google";
import { Providers } from "./redux/providers";
const ubuntu = Ubuntu({ subsets: ["latin"], weight: "500", display: "swap" });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
